name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Git user
        run: |
          git config --global user.email "mdmahamudmredha@gmail.com"
          git config --global user.name "mdmahamudmredha"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.Human_and_Forklift_Detection_HF_Token }}
        run: |
          git remote add space https://user:${HF_TOKEN}@huggingface.co/spaces/mdmahamudmredha/Human_and_Forklift_Detection
          git push space main --force
